"""empty message

Revision ID: db374284d5c6
Revises: 
Create Date: 2022-08-13 01:55:42.462390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db374284d5c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    op.execute('UPDATE task SET completed = False WHERE completed is NULL;')
    op.alter_column('task','completed',nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'completed')
    # ### end Alembic commands ###
